# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "executor" do |executor|
    executor.ssh.insert_key = false
    executor.vm.box = "bento/centos-7.1"
    executor.vm.hostname = "executor"
    executor.vm.network "private_network", ip: "192.168.34.20"
  end

  config.vm.define "web" do |web|
    web.ssh.insert_key = false
    web.vm.box = "bento/centos-7.1"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.34.21"
  end

end
