---
- name: Ansible Pull Mode
  hosts: pullhosts
  tasks:
   - name: Setup EPEL
     action: command rpm -ivh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm creates=/etc/yum.repos.d/epel.repo

   - name: Install Ansible + Dependencies
     yum: name={{ item }} state=latest enablerepo=epel
     with_items:
      - ansible
      - git-core

   - name: Make directory to put downloaded playbooks in
     file: state=directory path=/opt/ansiblepull

   - name: Setup cron
     cron: name="ansible-pull" user=root minute="*/5" state=present job="ansible-pull -U https://git.int.example.com.com/gitrepos/ansiblepull.git -D /opt/ansiblepull {{ inventory_hostname_short }}.yml"
