---
- name: Fetch configuration from all webservers
  hosts: webservers
  tasks:
   - name: Get config
     get_url: dest=configs/{{ ansible_hostname }} force=yes url=http://{{ ansible_hostname }}/diagnostic/config
     delegate_to: localhost
