---
- name: Registers the app server farm
  hosts: localhost
  connection: local
  vars:
    hostcount: 5
  tasks:
   - name: Register the webapp farm
     local_action: add_host name={{ item }} groupname=webapp
     with_sequence: start=1 end={{ hostcount }} format=webapp%02x
