---
- name: Install Ansible
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install pip
      yum: name=python-pip state=latest

    - name: Install Ansible
      pip: name=ansible state=present
