---
- name: Setup BIND
  hosts: allnames
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - name: configure BIND
     template: src=templates/named.conf.j2 dest=/etc/named.conf owner=root group=root mode=0640
